// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/rtp-processor/config"
	"github.com/rtp-processor/consumer"
	"github.com/rtp-processor/db"
	"github.com/rtp-processor/jackpot"
)

// Injectors from wire.go:

// InitializeApp 初始化应用程序（Wire生成代码）
func InitializeApp(cfg *config.Config) (*App, error) {
	gameConsumer, err := consumer.NewGameConsumer(cfg)
	if err != nil {
		return nil, err
	}
	pushConsumer, err := consumer.NewPushConsumer(cfg)
	if err != nil {
		return nil, err
	}
	clickHouseWriter, err := db.NewClickHouseWriter(cfg)
	if err != nil {
		return nil, err
	}
	mySQLManager, err := db.NewMySQLManager(cfg)
	if err != nil {
		return nil, err
	}
	manager, err := jackpot.NewManager(mySQLManager)
	if err != nil {
		return nil, err
	}
	app := &App{
		Config:       cfg,
		GameConsumer: gameConsumer,
		PushConsumer: pushConsumer,
		CHWriter:     clickHouseWriter,
		MySQLManager: mySQLManager,
		JackpotMgr:   manager,
	}
	return app, nil
}

// wire.go:

// App 应用程序（由Wire注入）
type App struct {
	Config       *config.Config
	GameConsumer *consumer.GameConsumer
	PushConsumer *consumer.PushConsumer
	CHWriter     *db.ClickHouseWriter
	MySQLManager *db.MySQLManager
	JackpotMgr   *jackpot.Manager
}
