// This file is generated by GoAdmin CLI adm.
package tables

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// Generators is a map of table models.
//
// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "game_config" => http://localhost:9033/admin/info/game_config
// "game_config_version" => http://localhost:9033/admin/info/game_config_version
// "integrator_config" => http://localhost:9033/admin/info/integrator_config
// "pay_table_config" => http://localhost:9033/admin/info/pay_table_config
// "reel_config" => http://localhost:9033/admin/info/reel_config
// "reel_symbol_weight" => http://localhost:9033/admin/info/reel_symbol_weight
// "symbol_config" => http://localhost:9033/admin/info/symbol_config
// "symbol_multiplier" => http://localhost:9033/admin/info/symbol_multiplier
// "symbol_special_property" => http://localhost:9033/admin/info/symbol_special_property
// "transaction_records" => http://localhost:9033/admin/info/transaction_records
// "user_finance_stats" => http://localhost:9033/admin/info/user_finance_stats
// "user_info" => http://localhost:9033/admin/info/user_info
// "user_overview" => http://localhost:9033/admin/info/user_overview
// "user_session" => http://localhost:9033/admin/info/user_session
//
// example end
var Generators = map[string]table.Generator{

	"game_config":             GetGameconfigTable,
	"game_config_version":     GetGameconfigversionTable,
	"integrator_config":       GetIntegratorconfigTable,
	"pay_table_config":        GetPaytableconfigTable,
	"reel_config":             GetReelconfigTable,
	"reel_symbol_weight":      GetReelsymbolweightTable,
	"symbol_config":           GetSymbolconfigTable,
	"symbol_multiplier":       GetSymbolmultiplierTable,
	"symbol_special_property": GetSymbolspecialpropertyTable,
	"transaction_records":     GetTransactionrecordsTable,
	"user_finance_stats":      GetUserfinancestatsTable,
	"user_info":               GetUserinfoTable,
	"user_overview":           GetUseroverviewTable,
	"user_session":            GetUsersessionTable,

	// generators end
}
